replicaCount: 3

image:
  repository: ghcr.io/mondu-ai/eks-pod-identity-webhook
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: aws-pod-identity-webhook-sa


certManager:
  enabled: true
  issuerName: aws-pod-identity-webhook-selfsigned-issuer
  secretName: aws-pod-identity-webhook-tls-secret
  certificate:
    duration: 2160h
    renewBefore: 360h

existingTLSSecret: ""

service:
  port: 443

nodeSelector:
  kubernetes.io/arch: arm64

affinity: {}

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  AWS_REGION: us-east-1
  GIN_MODE: release
