apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eks-pod-identity-webhook.fullname" . }}-cr
  labels:
    app.kubernetes.io/name: {{ include "eks-pod-identity-webhook.name" . }}
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch"]
