{{- if and .Values.certManager.enabled (not .Values.existingTLSSecret) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.certManager.issuerName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "eks-pod-identity-webhook.name" . }}
spec:
  selfSigned: {}
{{- end }}
