apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-pod-identity-webhook.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "eks-pod-identity-webhook.name" . }}
    app.kubernetes.io/instance: {{ include "eks-pod-identity-webhook.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "eks-pod-identity-webhook.name" . }}
    app.kubernetes.io/instance: {{ include "eks-pod-identity-webhook.fullname" . }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: webhook-https
      protocol: TCP
