apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gar-credential-provider.fullname" . }}
  namespace: {{ include "gar-credential-provider.namespace" . }}
  labels:
    {{- include "gar-credential-provider.labels" . | nindent 4 }}
